### ISSUE TITLE
Create a calendar app to manage schedule of equipment in fiber group

### ISSUE THREAD

**Issue by mmfiber** [6f-fiber-group/equipment-calender#1]
# Object
  * Manage the schedule of equipment for the more efficient experimental environment
  * To learn to go and docker
  * To learn to how to layout database

# Requirements
Some functions shown below should be included in the app of the first version. 
  * Sign up / Sign in
  * Create calendar
  * Switch calendar
  * SPA (vue router)
  * Add event

**Comment by mmfiber** [comment]
# Todos
  - [ ] learn to go (dotinstall, progate, some tutorials ...)
  - [ ] create dev env on VM with docker
  - [ ] deploy to heroku by new account
